shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 4*00 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
o [d8]f w y u|o h [od] 3 7|w|o h [so] 4 8 w [ti]|[wu] 8 [wt]y 5|5 as[ya] o y t [yw1]u 5 9 [wu]|w 9 [yw] 3 y 7 [yw]||0 pa[tsi2]|9 [yod3]|o w [sohd] 5 w t y o s d h v| |o|i|[yw1]u y [wu] [y5] [wu] i [wu8] [ywo] 3 7|w r t t [tp] 4 [p8] [wtp] [rp94] p o [ri] [yo] 3 7 w [wt6]|u [to] [ie] 4 [u8] [ie] [wu] 4 [yw] 9 w [ywo3] I [yo] [iT] [w6] u 0 [ie] 2 u [tie9] u [ie] u [wt] [wt]y|[ywt5] [ywt5]|5 5 [ywto] w [yw1]u y [wu] [y5] [wu] i [wu8] [ywo] [93]|9 w|t t [utp] 4 [p8] [wtp] [rp94] p o [ri] [yo] 3 7 w [wt6]|u o [tie] [82] u [ti] [uqe5] y q r w [ywo3] I [yo] [iT] [w6] u 0 [ie] 2 u [tie8] u [wt95]y t r t [tiW1] u y [yw]u 5 u [wu] [ut] 6 u [yw] [ut] 0 p [us] [ya] 3 [u7] [yw] [yw]u 7|[wu] o [utp4] p [tp] [ya94]|a [s9] [yto] [yt3] 8 w [rW0%]|u [ur] [ut] 6 [u0] [yw] [ut] 0 p [us] [ya] 3 [a7] [ywa] p [yro]|w u [tie82] u [ie] [wu3] [ie4] [of] [q4] [of] 5 [so]d [s9] [id] w 5 [us] o [od1]f f [wof] [tof] w o [o8] [yod] 3 [d7] [wod] [yod]|7 [wa] a [tso4] [tso8] [tsqo] [yqoda4]|a [yp] [ro] 3 7 r [wt6]|u [wu] [tie] 2 u [ie] [ywto5]|o [ro4] i [wu3] u o [wus6]|0 w sd[sif82] d s [od30] s [sqo4] d [so]d|5 5 [sohd] [sohd] [sig] 5 o [od1]f f [wof] [tof] w o [o8] [yod] 3 [d7] [wod] [yod]|7 [ywa] [ya] [tso4] [tso8] [tsqo] [yqoda94] 9 [ya] [yp] [ro] 3 7 r [wt6] 0 u [wu] [tie] 2 u [ie] [ywto5]|o [wro4] i [wu3] u [d7] [us] [w6]|w sd[sif82] d s [sod5] 5 s [si] [us] 4 8 w [yqoda4]|9 w as[yod3] h a [yso] @ ^ w|[utq82] i [ywto30] [id] [us]|4 8 w [ya]|w [tp] 8 [ywto5]|5 as[ya] o [yw] w [yw1]u y [wu] [y5] [wu] i [wu8] [ywo] 3 7|w r t t [tp] 4 [p8] [wtp] [rp94] p o [ri] [yo] 3 7 w [wt6]y|u [to] [ie] 4 [u8] [ie] [wu] 4 [yw] 9 w [ywo3] I [yo] [iT] [w6] u 0 [ie] 2 u [tie8] u [wt95]y t r t [tiW1] u y [yw]u 5 u [wu] [ut] 6 [u0] [yw] [ut] 0 [ya] [us] [tp] [ya3] [u7] [yw] [yw]u 7|[wu] o [utp4] p [tp] [ya94]|a [s9] [yto] 3 8 w [rW0%]|u [ur] [ut] 6 [u0] [yw] [ut] 0 [us] [tp] p [ya3] [a7] [ywa] [tp] 0 [yro] w u [tqie2] u [ie] [wu3] [ie4] [of] [q4] [uof] 5 [so][yod] [tsi9] [yod] 5 5 [us] o [od1]f f [wof] [tof] w o [o8] [yod] 3 [d7] [wod] [yod]|7 [ywa] [ya] [tsoi4] [tso] [tsqoi] [yqoda4] q a [yp] [ro] 3 7 r [wt6]|u [wu] [tie] [82] u [ie] [ywto5]|o [ro4] i [wu3] u o [wus6]||w sd[spif2] d s [od30] s [sqo4] d [so]d|5 5 [sohd] [sohd] [sig] 5 o [od1]f f [wof] [tof] w o [o8] [yod] 3 [d7] [wod] [yod]|7 [ywa] [ya] [tsoi4] [tsoi8] [tsqoi] [yqoda94] 9 [ya] [yp] [ro] 3 7 r [wt6] 0 u [wu] [tie] 2 u [ie] [ywto5]|o [wro4] i [wu3] u [d7] [us] [w6]|w sd[sif2] d s [sod5] 5 s [si] [us] 8 w t [yo]|[ti] W o [od8]f [wf] f [of] t o o [od] 0 [rd] d [od] y|a a [sqo] s [si] [yqida]|o [pj] [pjd] 3 [ohd] 7 [wt6] 0u u [tie] 2 u [ie] [ywto5]|o [wro4] i [ywu3] u [yod%] [us] [w6] 0 w sd[sif82] d s [sod5] 5 s [si] [us] 1 5 9 [tq]|0|sd[sif9] d s [wod]d| |5 5| |d s [ywso8]|||[ywto81]
]]