shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 2*52 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
YigPiDYiPPiDYigPiDYiPPiDYigPiDYiPPiDYigPiDYiPPiD[dY]igPiDYiPPiD[sY]igPiD[YP]iPPiP[YD]igPiDYiPPiD[dY]igPiDYiPPiD[td]igPiDtiPPiD[ts]igPiD[tP]iPPiD[tg]igPiDtiPDiD[td]igPiDtiPPiD[dY]igPiDYiPPiD[sY]igPiD[YP]iPPiP[YD]igPiDYiPPiD[dY]igPiDYiPPiD[td]igPiDtiPPiD[ts]igPiD[tP]iPPiD[tg]igPiDtiPPiDtigPiP[tD]iPPiD[gW%]igPiDYiPPiDYigPiP[YD]iPPiD[wg5]igPiDYiPPiD[hY]ggPgD[jY]gPPgD[j@(]ggPgD[YJ]gPPgD[hY]ggPiD[gY]iPPiD[hY]igPiDYiPPiDYigPiDYiPPiP[WD%]ig[YWP]iD[YW]iP[YWP]iD[YW]ig[YWP]iD[gYW]iP[YWP]iD[wd5]ig[wYP]iD[wY]iP[wYP]iD[wY]ig[wYP]iD[wYP]iP[wYP]iD[d81]ig[wtP]iD[wt]iP[wtP]iD[wt]ig[wtP]iD[wt]iP[wtP]iP[D!]ig[WTP]iD[WT]iS[WTP]iD[WT]ig[WTP]iD[WT]iS[WTP]iD^ig[qPE]iD[qE]iS[qPE]iD[qE]ig[qPE]iD[qE]iS[qPE]iD$PJ[SQ]PH[Q]SG[SQ]PH[Q]PJ[SQ]PH[Q]SG[qS]PH@PJ[^S(]PH[^(]SG[^S(]PH[^(]PJ[^S(]PH[^(]SJ[D]aL7DZ[rG(]DL[r(]Gk[rG(]DL[r(]DZ[rG(]DL[r(]Gk[GE(]DL%DZ[WH(]DL[W(]Gk[WH(]DL[W(]DZ[WH(]DL[W(]GZ[HE(]Gc[@(]gc[YJE]gZ[YE] J[YJE]DZ[YE]gc[YJE]gZ[YE] J[YJE]DZ[YE]gc[YJE]gZ[YE] J[YJE]DZ[YE]gc[YJE]gZ[YE] J[YJE]DZ[yZJ(]gcJ[g(]Z[ZJ]g[J(]JDZ[tZJ(]gcJ[g(]Z[ZJE]g[J(]JDZ[ZYJ(]gcJ[g(]Z[ZJ]g[J(]JDZ[yZJ(]gcJ[g(]Z[ZJ]g[J(]JDZ[yZJ(]gcJ[g(]Z[ZJ]g[J(]JDZ[tZJ(]gcJ[g(]Z[ZJE]g[J(]JDZ[iZJE]gcJ[g(]Z[ZYJ]g[J(]JDZ[yZJ(]gcJ[g(]Z[ZJ]g[J(]JDZ[yZWH(]gcJ[gW(]Z[ZH]g[WJ(]JDZ[tZWH(]gcJ[gW(]Z[ZHE]g[WJ(]JDZ[tZYWH]gcJ[tgW]Z[ZH]g[tWJ]JDZ[yZWH]gcJ[tgW]Z[ZH]g[tWJ]JDZ[zywhE]gcJ[wgE]Z[zh]g[wJE]JDZ[zwth9]gcJ[wg9]Z[zhE]g[wJ9]JDZ[zwihE]gcJ[wgE]Z[zh]g[wJE]JDZ[zwhE]gcJ[wgE]Z[zhY]g[wJE]JDZ[tiZWH]gcJ[tgW]Z[ZH]g[tWJ]JDZ[tZWH]gcJ[tgW]Z[ZYH]g[tWJ]JDZ[zyqiJE]gcJ[ygE]Z[zJ]g[yJE]JDZ[zyJE]gcJ[ygE]Z[zoJ]g[yJE]JDZ[toZWH]gcJ[tgW]Z[ZOH]g[tWJ]JDZ[tZYWH]gcJ[tgW]Z[yZH]g[tWJ]JDZ[tZYWH]gcJ[tgW]Z[ZH]g[tWJ]JDZ[tZWH]gcJ[tgW]Z[ZH]g[toWJ]JDZ[tqolH]gcJ[tqg]Z[lOH]g[tqJ]JDZ[tqlYH]gcJ[tqg]Z[ylH]g[tqJ]JDZ[tqlYH]gcJ[tqg]Z[lH]g[tqJ]JDZ[tqlH]gcJ[tqg]Z[liH]g[tqJ]JDZ[ywlH9]gcJ[wg9]Z[lH]g[wJ9]JDZ[wlH9]gcJ[wg9]Z[tlH]g[wJ9]JDZ[wrkh9]hvk[wh9]z[kh]d[zw9]hdh[wrhd9]ahd[wra9]d[oa]y[wrd9]oyo[oa5]ydo[y5]o[oa]y[d5]oyo[oa5]ydo[y5]o[oa]y[d5][wo]yo158(wt
]]