shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 2*50 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[uspf6] 6||[spig6] 6||[spoh6] 6||[spig6] 6||[uspf6]|||[u6] [t0] e [u0] [i4] [t0] e [i0]u[y5] [r9] w [y9] [u8] [wr] w [yw]t[e4] [t0] u [t0] [y4] [r9] w [t9]y[Y$] [r(] e [Y(] [u3] [y0] [r9] [W7] [u6] [t0] e [u0] [i4] [t0] e [i0]u[y5] [r9] w [y9] [u8] [wr] w [yw]t[e4] [t0] u [E0] [r$] [e(] u [e(] [W3] [y9] u [ye9]r[te8]| |p [sf] [jf] l [kh] d [ha] d [ji] [sp] [sg] j h|f|[yg] [pi] [pd] g [sf] p [sp] p [dO] [pi] [sa] [aO] [sp] u p u 6 [tf] j [tl] [k5] [rd] h [rd] [j4] [se] g [je] [h8] u|u [g2] [qp] d [qg] [f6] [tp] s [tp] [d3] [iW] O [dW] [s6] t [sf] t [ugda]|[sf][da][sp][ufaO]|[daH]|[faH]||[sj][kd][uspj]|[sf]|[rgd]|[sf][da][sp][uaWO0]|[rdaO]|[urO]||[tp][ya][tpe0]| |@ 3 8 [W7] [r9] [t(] [yq] [u0] [xpj]| |[pjc]| |[vpj]|3|[pjc]| |[xpj]|||[u6] t e u [i4] t e i [o5] t e o [i3] r W i [u6] t e u [i4] t e i [o5] t e o [i3] r W i [uhe]Hjt e u [qi] t e i [woh] t e [oj] [li0] [zr] [lW] [ji] [ue] t e u [qi] t e i [wo] t e o [i0] r W i [uhe]H[sj]t e u [qi] t e i [woha] t e [soj] [lif0] [zrg] [lfW] [xli] [ue] t e [ujc] [qi] t e i [wvok] t e o [kiH0] r W i [ulje] t e u [qi] t e i [wo] t e o [i0] [rpg] [haW] [pig] [uofe] [ta] [tpe] u [qi] t e i [woda] t e [spo] [i0] r [aWO] i [upe] [ta] [se] [uf] [qji] [tf] [se] [ia] [woda] t e [spo] [i0] r [aWO] i [sf6][sf] [sf][sf] [sp][sp] [sp][sp] [da3][da] [da][da] [aO][aO] [aO][aO] [sp6][sp] [sp][sp] [tp][tp] [tp][tp] [uO3][uO] [uO][uO] [aO][aO] [da][da] [sf6][sf] [sf][sf] [sp][sp] [sp][sp] [da3][da] [da][da] [aO][aO] [aO][aO] [sp6][sp] [sp][sp] [tp][tp] [tp][tp] [uO3][uO] [uO][uO] [aO][aO] [da][da]| |[sp]|[xlj]| |Z [ljc]|x| |Z[zH]| |[hL]| |[lG6]
]]