shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 5*18 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[fe]jl[uk] [pj] [ha] [sjih]||[jgd9] [he] [ig] [ed] [tsof8]|[woda5]|[usp4] [a8] [sq] f [oda5] 9 a o [ypo2] 6 9 6 [ypo9]|[uaWO%]|[usp6] [a0] [pe] [ro] [tqpo]||[ypi2] [o6] [i9] [y6] [wut8]|[ywr5]|[te20] [r6] [t9] [ue] [y3] 7 [yro0]|[tpo4] 8 w e u i s f j|||[utse] a s f [yied]|[ywra] o [utpe]|||[utse] d f j [yeI] h G d [f3] 7 0 e [wur]|f h [qj] t [pk]|[h0] t o f [g9] [fe] [ig] [je] [h6] 0 [tf] d [s9] e y I|p a s [d^] q [iE] [yq] [ure0]|[W3] a [s6] [a0] [ts] [f0] [d9] e [ya] o [p6] 0 e r t u p a [s6] [d0] [tf] [j0] 9 [he] [IG] d [f3]|0 e [wur]|f h [qj] t [pk]|[h0] t o f [g9] [fe] [ig] j [h6] 0 t|[s4] [a8] [se] [uf] [d5] 9 [ra] o [p6] 0 e t u p s f sfj|||[f8] w [uh] w [G9] e I|8 [wf] [uh] [wj] [G9] [fe] [dI]|[f6] 0 e y|0 e y [T6] 0 e T||6 7 [f8] w [uh] w [G9] e I|8 [wf] [uh] [wj] [G9] [fe] [dI]|[f3] 7 0 e r u p a [urO0]|||[f30] h [qj] t [pk]|[qh] t o f [g9] [fe] [ig] j [h6] 0 t|[s4] [a8] [se] [uf] [d5] 9 [ra] o [p6] 0 e t u p a s [fe]jl[uk] [pj] [ha] [sjih]||[jgd9] [he] [ig] [ed] [tsof8]|[woda5]|[usp4] [a8] [sq] f [oda5] 9 a o [ypo2] 6 9 6 [ypo9]|[uaWO%]|[usp6] [a0] [pe] [ro] [tqpo]||[ypi2] [o6] [i9] [y6] [wut8]|[ywr5]|[te20] [r6] [t9] [ue] [y3] 7 [yro0]|[tpo4] 8 w e u i s f j|||[sl8] w t [zud] [xof] u [vth] w [zd7] w r y o|[sl] [ka] [pj4] 8 e u [yre5]|[oh] [pj] [pj2] 6 9 Q e|y [ka] [sl8] w t [zud] [xof] u [vth] w [zd7] w r y o||[sl] [zd^] q E [yxf] [igc] y [jbE] q [xkhf3] 7 [ywoa]|[upeS6] 0 [xjfL6]|[ljcb4] 8 q e t i p a [spi9] t y|[xwljb5]|[zyvrokh]|[xkhf3] 7 0 w r y [zokhd]|[sljf6] 0 e r t|[zwvkh5]|[ljcb4] 8 q e t i p a [spi9] e y|[xwljb5]|[zyvrokh]|[zjcb3] 7 0 e r u p a [upeS6] 0 [rdaI7] Q [ofTS*]|[xjfeL6]|[ljcb4] 8 q e t i p a [spi9] e y|[xwljb5]|[zyvrokh]|[xkhf3] 7 0 [xwvkh] r y [xokhf]|6 0 e r t|[xwkhf5]|[ljcb4] 8 q e t i p f [ypied9]||[yxvroml]|[zwvnk5]|[xljb6]|||[ute60]||[yeI]|||[uoe60]|[60] [yeI] [Q6]|[Q6]|[wuoe6]|[yweI6]|[uteQ6]|[ydQ6] [ts][yd][uspf6]||[yeI]|||[wute6]|[w6]|[yeQI6]|[yteQ6]|[utqp4]||[wur30]|o|[yie92]|u|[ywr81]|t|[r7] $ 7 ( Q r Y I [urO30] 7 [W30] 7 [rW30] 7 [urW30] 7 [uTO!] % * [uaO0] [uaWO] T [uS]|[aTI$] Q r T [QPE]||[zd7]Q[rSL]y[zdI]y[rGC]Q[xf0]wru[SL6]0[pje]T[ka7]QruyIaSdSaIyTrQ[zd7]Q[xrf]y[IGC]y[rnk]Q0W[rjb]u[VOH]u[xrf]w[GC$]|r T [eTI]|[GC] [jb] [wnk]ryo[aL]oyr[jbQ]eyIpI[yGC]e[vh0]w[rGC]u[voh]u[rnk]w[jb0]eyIpIye[zd5]9[wSL]r[zyd]r[wGC]9[xf6]0eT[uSL]T[pje]0[ka7] $ 7 9 QryI[aGC]I[yjb]r[wnk]ryo[aL]oyr[jbQ]eyIpI[yGC]e[vh0]w[rGC]u[voh]u[rnk]w9e[yjb]IpIye[zd5]9[wSL]r[zyd]r[wGC]9[xf6]0eTuT[zed]0[xf$][ZQD]e[xfT]e[jbQ][GC7]QrYIaDG[vh0]w[rGC]u[voh]u[rnk]w[jbQ]eTI[GC$]*Qe[zvnk5]|[urQ]|[yoa]|[khd]|[znC]||z|L|[zr]Cn[LI] [ka] [jS] [okjd]||[khf0] [rj] [uh] [rf] [ypdG9]|[pfeS6]|[daI5] [S9] [wd] G [pfS6] 0 S p [upa3] 7 0 7 [upaW]|[^SPIE]|[d7]Gkz[SQL] [rka] [pjT] [ywka]||[o3]fhk[pj7] [oh0] [uf7] [yIG9]|[ueQ60]|[y5]oad[TS9] [ywd] [IG9] [upfeS6]|[pjfSQ$]|[kfa7] $ 7 0 Q r u I [rYTQ7]
]]