shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 2*48 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[hfe]puepu[kd0] [hfe]puepu[kd0]
[hfe]puepu[kd0] [hfe]p[uda][sf]e[da][sp]u[da0]
[hfe]puepu[kd0] [hfe]puepu[kd0]
[hfe]puepu[kd0] [hfe]p[uda][sf]e[da][sp]u[da0]
[qhf]itqit[kd0] [qhf]itqit[kd0]
[qhf]itqit[kd0] [qhf]i[tda][sf]q[da][spi]t[da0]
[qhfuu] u]itqit[kd0] [qhf]itqit[kd0]
[qhf]itqit[kd0] [qhf]i[tda][sf]q[da][spi]t[da0]
[hfe]puepu[kd0] [hfe]puepu[kd0]
[hfe]puepu[kd0] [hfe]p[uda][sf]e[da][sp]u[da0]
[hfe]puepu[j0]J[kd][hfe]puepu[J0][kd]
[hfe]puepu[zn0] [meb]p[vun][mb]e[vn][xpb]u[vn0]
[qm]itqit[n0] [vq]itqit[c0]
[xq]itqit[z0] [ql]i[zt]lqz[xi]t[c0]
[vq]itqit[l0] [qb]itqit[l0]
[qn]itqit[l0] [qmb]i[vtn][mb]q[vn][xib]t[vn0]
[hfe]puepu[kd0] [hfe]puepu[kd0]
[hfe]puepu[kd0] [hfe]p[uda][sf]e[da][sp]u[da0]
[hfe]puepu[j0]J[kd][hfe]puepu[J0][kd]
[hfe]puepu[zn0] [meb]p[vun][mb]e[vn][xpb]u[vn0]
[qm]itqit[n0] [vq]itqit[c0]
[xq]itqit[z0] [ql]i[zt]lqz[xi]t[c0]
[vq]itqit[l0] [qb]itqit[l0]
[qn]itqit[l0] [qmb]i[vtn][mb]q[vn][xib]t[vn0]
[lj9]ye9ye9 [lj9]y[khe][lj]9[kh][yjg]e[kh9]
[lj0]ur0ur0 [lj0]u[rkh][lj]0[kh][ujg]r[kh0]
[qlj]itqit[qkh] [qhf]itqoy[gdO]
[sfe]puepu[eda] [wsp]o[yda]w[sof]y[wgd]
[hf9]y[hfe]9[yhf]e[hf9] [hf9]ye9[ysp]e[sf9]
[da0]u[rda]0[uda]r[da0] [da0]ur0[usf]r[da0]
[sq]itqit[uqo] [sqf]i[tgd]q[oda]yO[sp]
[spe]puepu[oe] [ws]o[yd]w[of]y[wg]
[ih] [sph] [th] [sph] [ih] [sp] [ts] [spf]
[od] [da] [yd] [da] [od] [da] y [fda]d
[sp] [sf] [us] [sf] [sp] [sf] [uk] [slf]
[ok] [da] u [hda] [od] [da] u [fda]g
[ih] [sph] [th] [sph] [ih] [sp] [ts] [spf]
[od] [da] [yd] [da] [od] [da] [yf] [da]
[sf] [hf] [of] [hf] [sf] [hf] [og] [hf]
[od]| [oh] [sl] [zd] [xf] [gc]
[vhe] [vuth] [vhe] [vuth] [vhe] [ut] [sle] [xutf]
[zwd] [zyrd] [zwd] [zyrd] [zwd] [yr] w [yxrf][zd]
[sql] [tsle] [sql] [tsle] [sql] [te] [qnk] [tmle]
[nk0] [yr] 0 [yvrh] [zd0] [yr] 0 [yxrf][gc]
[vhe] [vuth] [vhe] [vuth] [vhe] [ut] [sle] [xutf]
[zwd] [zyrd] [zwd] [zyrd] [zwd] [yr] [xwf] [zyrd]
[sql] [te] q [tohe] [xwf] [yrgc] [zwd] [yr][sl]
[tsl] [uo] t [uo] [tsf] [uogd] [tda] [uspo]
[tsp] [uo] t [uo] [tsf] [uogd] [tda] [uo][sp]
[utspo]| [uo] [sf] [gd] [hf] [kh]
[hf]| [kd] [hf]| [kd]
[hf]| [kd] [hf] [da][sf][da][sp] [da]
[te]puepu0 epue[wp]u[y0]
ep[ut]epu[t0] ep[ur]epu[r0]
ep[ut]epu[o0] epuepu[u0]
epue[sp]u[u0] [ea]pue[po]u[y0]
[wrq]it[tqe]it[ut0] [qpi]it[sqp]it[oa0]
[uqo]itqit0 [utq]itq[tie]t0
[yrq]it[utq]it[ut0] qitq[ie]t[y0]
qitqit0 [tq]itq[ri]t0
[te]puepu0 epue[wp]u[y0]
ep[ut]epu[t0] ep[ur]epu[r0]
ep[ut]epu[o0] epuepu[u0]
epue[sp]u[u0] [ea]pue[po]u[y0]
[wrq]it[tqe]it[ut0] [qpi]it[sqp]it[oa0]
[uqo]itqit0 [utq]itq[tie]t0
[yrq]it[utq]it[ut0] qitq[ie]t[y0]
qitqit0 [tq]itq[ri]t0
[slj9]ye9ye9 [lj9]y[khe][lj]9[kh][yjg]e[kh9]
[lj0]ur0ur0 [lj0]u[rkh][lj]0[kh][ujg]r[kh0]
[qlj]itqit[qk] [qhf]itqoy[gO]
[sfe]puepu[eda] [wsp]o[yda]w[sof]y[wgd]
[hf9]y[hfe]9[yhf]e[hf9] [hf9]ye9[ysp]e[sf9]
[da0]u[rda]0[uda]r[da0] [da0]ur0[usf]r[da0]
[sqp]itqit[uqo] [sqf]i[tgd]q[oda]yO[sp]
[spe]puepue [wjg]oyw[okh]yw
[slj9]ye9ye9 [lj9]y[khe][lj]9[kh][yjg]e[kh9]
[slj0]ur0ur0 [lj0]u[rkh][lj]0[kh][ujg]r[kh0]
[sqlj]itqit[qk] [qohf]itqoy[gO]
[usfe]puepu[eda] [wsp]o[yda]w[sof]y[wgd]
[hf9]y[hfe]9[yhf]e[hf9] [hf9]ye9[ysp]e[sf9]
[hda0]u[rhda]0[uhda]r[hda0] [hda0]ur0[usjf]r[hda0]
[sqpf]itqit[uqo] [sjf] [kgd] [hda] [spf][spf]
]]