shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 3*54 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[tuo] [tuo] [tuo] [tuo] [yip] [yip] [yip] [yip] [etu] [etu] [etu] [etu] [qet] [qet] [qet] [qet] t u [of] [uh] [th] [uf] [of] u t y [is] [pd] [id] [ys] [is] p e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qd] [ef] [tf] e t u [of] [uh] [th] [uf] [of] u y i [ps] [id] [yd] [is] [ps] i e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qd] [ef] [tf] e t u [of] [ul] [tl] [uh] [oh] u y i [pf] [ih] [yh] [ij] [pj] i e t [uf] [th] [eh] [tf] [uf] [th] [qh] [es] [ts] [ed] [qd] [es] [ts] e t u [of] [uh] [th] [uf] [of] u y i [ps] [id] [yd] [is] [ps] i e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qeid] [ps] [qets] [pf] [tusf] f [tush] f [tusf] f [tudh] [fg] [yidj] g [yigj] g [yidj] g [yigj] [gh] [etps] s [etpf] s [etps] s [etfg] [sj] [qeip] p [qeis] p [qeip] p [qesl] [pl] [tusf] f [tush] f [tusf] f [tush] [fz] [yidj] g [yigj] g [yidj] g [yijl] [gl] [etsv] s [etpf] s [etsx] s [etfl] [sj] [qeps] [8l] [wv] [qc] [9x] [8z] [tshz] u o u t u [ol] [ux] [ydgj] i p i [wyv] [qic] [0px] [9iz] [epfz] t u t e t [ul] [tx] [qips] e t e [wv] [qc] [0tx] [9ez] [tshz] u o [uz] t u [oz] u [ydgj] i p [8il] [wyv] [qic] [0px] [9iz] [epfz] t u [tz] e t [uz] [tl] [qips] e t [8l] [wv] [qc] [0tx] [9ez] [tshz] u o u t u [ol] [ux] [ydgj] i p i [wyv] [qic] [0px] [9iz] [epfz] t u t e t [ul] [tx] [qips] e t e [wv] [qc] [0tx] [9ez] [tshz] u o [uz] t u [oz] u [ydgj] i p [il] [wyv] [qic] [0px] [9iz] [epfz] t u [tz] e t [uz] [tl]
t u [of] [uh] [th] [uf] [of] u t y [is] [pd] [id] [ys] [is] p e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qd] [ef] [tf] e t u [of] [uh] [th] [uf] [of] u y i [ps] [id] [yd] [is] [ps] i e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qd] [ef] [tf] e t u [of] [ul] [tl] [uh] [oh] u y i [pf] [ih] [yh] [ij] [pj] i e t [uf] [th] [eh] [tf] [uf] [th] [qh] [es] [ts] [ed] [qd] [es] [ts] e t u [of] [uh] [th] [uf] [of] u y i [ps] [id] [yd] [is] [ps] i e t [us] [td] [ed] [ts] [us] t q e [ts] [es] [qetd] s [sf] f [tuo] d g [yip] f h [etu] g j [qet] l l [tuo] h z [yip] l l [etuv] x l j [qet] [8l] [wv] [qc] [9x] [8z] [tshz] u o u t u [ol] [ux] [ydgj] i p i [wyv] [qic] [0px] [9iz] [epfz] t u t e t [ul] [tx] [qips] e t e [wv] [qc] [0tx] [9ez] [tshz] u o [uz] t u [oz] u [ydgj] i p [8il] [wyv] [qic] [0px] [9iz] [epfz] t u [tz] e t [uz] [tl] [qips] e t [8l] [wv] [qc] [0tx] [9ez] [tshz] u o u t u [ol] [ux] [ydgj] i p i [wyv] [qic] [0px] [9iz] [epfz] t u t e t [ul] [tx] [qips] e t e [wv] [qc] [0tx] [9ez] [tshz] u o [uz] t u [oz] u [ydgj] i p [il] [wyv] [qic] [0px] [9iz] [epfz] t u [tz] e t [uz] [tl]
[0eul] [0eu] k [0eu] [0euh] [8qt] [8qtl] l [8qtl] l [8qtl] l [wtol] [wto] k [wto] [wtoh] [9wy] [9wyl] l [9wyl] l [9wyl] l [0euz] x [0eu] z [0eu] [0eul] [8qt] [8qtl] l [8qtl] l [8qtl] l [wtoz] x [wto] z [wto] [wtok] w r y [8l] [wv] [qc] [0yx] [9rz] [tfz] [uf] [od] [ud] [tf] [uf] [odl] [udx] [yg] [ig] [pf] [if] [ygv] [igc] [pfx] [ifz] [esz] [ts] [up] [tp] [es] [ts] [upl] [tpx] [qp] [ep] [ti] [ei] [qpv] [epc] [tix] [eiz] [tfz] [uf] [od] [udz] [tf] [uf] [odz] [ud] [yg] [ig] [pf] [ifl] [ygv] [igc] [pfx] [ifz] [esz] [ts] [up] [tpz] [es] [ts] [upz] [tpl] [qp] [ep] [ti] [eil] [qpv] [epc] [tix] [eiz] [tfz] u [od] u [tf] u [odl] [ux] [yg] i [pf] i [ygv] [ic] [pfx] [iz] [esz] t [up] t [es] t [upl] [tx] [qp] e [ti] e [qpv] [ec] [tix] [ez] [tfz] u [od] [uz] [tf] u [odz] u [yg] i [pf] [il] [ygv] [ic] [pfx] [iz] [esz] t [up] [tz] [es] t [upz] [tl] [qp] e [ti] e [qp] e [ti] e [0eul] [0eu] k [0eu] [0euh] [8qt] [8qtl] l [8qtl] l [8qtl] l [wtol] [wto] k [wto] [wtoh] [9wy] [9wy] [9wy] [9wy] [0eul] [0eu] k [0eu] [0euh] [8qt] [8qtl] l [8qtl] l [8qtl] l [wtoz] x [wto] z [wto] [wtok]
]]