shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 2*49 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[r6] t r t r t e r e r t e [t64] y t y t y r t r t y u [r6] t r t r t e r e r t e [t64] y t y t y r t r t y u [ra6] t [r0] t [re] t [ue] r e r t e [t6] y [tq] y [te] y r [ti] [ro] [tp] [ya] [us] [ra6] t [r0] t [re] t [ue] r e r t e [t6] y [tq] y [te] y r [ti] [ro] [tp] [ya] [us] [f2] u [qie9] u [yqie] p [ud2] i [yqe9] u [yqpe]|[f5] u [wri9] u [ywri] p [ud5] i [ywrh] u [ywr] s [a1] r [t80] r [wt0] u [r1] t [e80] r [w0]|[a3] u [spe0] u [yeda] p [uf3] O [raW0] u [rWO0]|[i4]pfy [uq8] p [yqe] u [i4]pdy [uq8] p [tqe]|[oda5]|[wroa9]|[ywsr]|[od5]|[wsr9]|[ywr] a [oa1] y [wut] a [r0] y [uo1] y [wut] a [r0] y [ut6]|[pe0]|[tea]|[s6]|[wa0]|[tpe]|[f4]jx|[tqe]|[ute]|[zjd4]|[tqe]|[ute]|[o5]ad|[wrkda9]|[ywsl]|[zhd5]|[wsrl9]|[yw] [ka] [kfa1]|[wr0]|[wut]|[ohfa1]|[wr0]|[wut]|[ka3]|0 r [pje] r [O0][ra][uf]H| |[r60] t r t r t [e0] r e r t e [tq64] y t y t y [rq] t r t r t [r60] t r t r t [e0] r e r t e [tq64] y t y t y [rq] t r t r|[ka6] u [ta0] s [uea] u [uf6] u [ta0] s [upe] u 6 i [tqa] s [iea] i 6 [ig] [tqoh] [pj] [kiea] [sl] [ka6] u [ta0] s [uea] u [uf6] u [ta0] s [upe] u 6 i [tqa] s [iea] i 6 [ig] [tqoh] [pj] [kiea] [sl] [xjf2] u [qi9] p [uqe] i [zd2] u [qi9] p [qpje]|[xjf5] u [wri9] p [ywur] i [zd5] 9 [wvh] e [wr] [sl] [ka1] r [t80] u [wr0] t [e1] r [w80] e [wr0]|[ka3] 7 [sl0] e [zrd] e [f3]Hkx [urW]|0|[tqed9] f d f d f [rqd9] f d f [ed] f [tqed9] f d f d f [rqd9] f h z [wk7]|[wrd80] f d f d f [ed80] f d f [d0] f [wd80] f d f d f d f k f d|[si9] q e y i|[ia9] q e y [pi]|[si5] 9 w e r|[ia5] 9 w e [yro]|[uta1] 5 8 w u|[tp1] 5 8 w [ut]|[ro51] 8 w t u o [ua]
]]