shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 4*02 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[VH6]| |[VH]| |[xf]| |[SL9]| |[SL]| |[pj]| |[H6] L j L H L j L f L j L j L j L [S9] L G L S L G L j L G L j L G L 6 0 [eS] a % [p0] [WO] p $ * Q|3 7 [p0] O [I2] [I6] [I9] u 3 [u7] [I0] T 6 0 e r T| |6 0 [eS] a % [p0] [WO] p $ * Q|3 7 [I0] u [I2] 6 [S9] a 3 7 [a0] p 6 0 e r T| |6 0 [eS] a % [a0] [WS] p $ * Q|3 7 0 u [p2] 6 [p9]|[O3] [p7] [O0] u 6 0 e r T|p a [S6] 0 [eS] a % 0 [fW] G $ * [SQ] p 3 7 [I0] p 2 6 [S9] a 3 [p7] [O0] p 6 0 e r T|I p [S9] [ea] [yS] a [S0] [rG] [uf] S [a*] W [TS]|$ * [QI] p [S7] [aQ] [rS] f [S3] [a7] [a0] p 6 [S0] e r T|p a [S9] [ea] [yS] a [S0] [rG] [uH] j [H*] WfTa [S$] * [SQ] p [I7] Q [rp] S [a3] 7O0u [I$] * Q| |[I9] e [yp] S [a0] r u|9 e [yT] I [O0] r [up] a [s8] [wa] [tp] j [k9] [he] y d [k0] r [ul]| |p a [se6] a p j [rk7] h d a [TS*]| |6 0 [eS] a % [a0] [WS] p $ * Q|3 7 [I0] p 2 6 [G9] f 3 [a7] [d0] S 6 0 e r T|p a [S6] 0 [eS] a % 0 [fW] G $ * [SQ] p 3 7 [I0] p 2 6 [f9] S 3 [a7] [p0] p [a6] [p0] e r T|I p [S9] [ea] [yS] a [S0] [rG] [uf] S [a*] W [TS]|$ * [QI] p [S7] [aQ] [rS] f [S3] [a7] [a0] p 6 [S0] e r T|p a [S9] [ea] [yS] a [S0] [rG] [uH] j [H*] WfTa [S$] * [fQ] S [a7] Q [rp] S [d3] 7S0a $ [p*] Q| |p a [S9] e [yG]|[f0] r [ua]|[S6] 0 e T u|p a [S9] e [yG]|[f0] r [ua]|[S6] 0 e u||p a [s2] 6 [qf]|[d3] 7 [hW]|[f4] [k8] e j||p o [p9] e [yf]|[d0] r [uo]|[p6] 0 e u| |[fH][L6] 0 e Gj[L%] [z0] [WL] k [H$] * [jQ]|3 7 [H0]|[G2] 6 9 H [j3] [H7] [G0] f [S6] 0 [fe] r [TS]dfGHj kLz [kW%]| |[zT] L g H [kQ$]|[j30]|[pYI@(]||IO[p7]r[a7]r[S7]r[G7]r[S%]W[G%]W[H%]W[j%]W[k!]!![L!][H!]!!![!]| |I p [S9] [ea] [yS] a [S0] [rG] [uf] S [a*] W [TS]|$ * [QI] p [S7] [aQ] [rS] f [S3] [a7] [a0] p 6 [S0] e r T|p a [S9] [ea] [yS] a [S0] [rG] [uH] j [H*] WfTa [S$] * [fQ] S [d7] Q [rI] S [d3] 7f0 p$ pQ| |I p [S9] [ea] [yS] a [S0] [rG] [uf] S [a6] 0 [eS] T u|I p [S9] [ea] [yS] f [S0] [ra] [ua] p 6 [S0] e u||p a [S9] [ea] [yS] a [S0] [rG] [uH] j [H] WfTa [S$] * [fQ] S [d7] Q [rS] d [S0] r [ua]|[p6] [p0] e u| |6 0 [eS] a % [p0] [WO] p $ * Q|3 7 [p0] O [I2] [I6] [I9] u 3 [u7] [I0] T 6 0 e r T| |6 0 [eS] a % [a0] [fW] S $ * Q|3 7 [I0] u [I2] 6 [S9] a 3 7 [a0] p [uT6] [e0] [uT] e [uT] e [uT] e [uT74] e [uT] e [uT] e [uT] e [ueT60*]
]]