shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 4*35 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
d h j [J(] w t Y|D J l [qJ] t Y [ji] ( [ts] [gY] [ih] [j9] q e t|s j J [j5] 9 [wJ] [hE] 7 [wa] [sr] [yd] [g(] w [tD] [YD]|I o d [s2] 6 [P9] [pQ] e y I P [tp5] 9 w [yoE] w 9 e E [whdP9]| |o p [P8] [wP] [tP] [YP]|[wP] t [YP] q [ts] Y i||i o [p^] [qp] [tp] [yp]|[qP] e [oE] ( w y Y||Y i [o8] [wo] [to] [oY]|[wo] t [yo] [o9] e [tI] [yo]|p|y 5 9 e E|9 e E 5 9 e E y|o p [P8] [wP] [tP] [YP]|[wP] t [YP] 4 [s8] ( q e|i d ^ [qd] [dE] [yg]|[ge] t [ys] ( [PE] Y i||o p [P8] [wP] [tP] [yP]| |p [P6] ( [sE] [td]|D|d 2 6 9 w e y o p [tI2] 6 9 Q [se] Q [d9] 6 [D8] [wD] [yD] [YD]|[yd] [ts] [PE] [qp] t [pY] [iP]|[sE] t [yd] ^ [qD] [td] [yD] d [sY] [yP] [tp] [o@] ^ q w E o p P [s8] [ws] [ts] [ys]|[PE] [pe] [wo] [I9] e [tI] [yo]|[pe] t y [s5] 9 [eP] [PE] y s d d 5 9 w r s 9 [wd] r [D8] [wD] [yD] [YD]|[yd] [ts] [PE] [qp] t [pY] [iP]|[sE] t [yd] ^ [qD] [td] [yD] d [sY] [yP] [tp] [o@] ^ q w E o p P [s8] [ws] [ts] [ys]|[PE] [pe] [wo] [I9] e [tI] [yo]|[pe] t y [p5] 9 [pe] [pE] y P|o [whd5]| |d h j [J(] w t Y|D J l [qJ] t Y [ji] ( [ts] [gY] [ih] [j9] q e t|s j J [j5] 9 e [yh] ^ [PE] [yD] [ig] [h8] w t Y|P h j [h9] e t [yG]|e [tD] y [odP5] 9 e E|9 e E [yroa5] 9 w e r [yqd] [oh(] [pj9] [JD1] 5 8 [JD(]|[d5] [JD8] [wlD] [JD4] 8 e [jD4] @ [s8] [ge] [h@] [sj2] 6 9 [sqj] e [s6] [sj9] [qdJ] [jP5] 9 [wJ] [rha]|5 [ws] [ed] [gd8] w [ysD] [sYD]|[wI] [yo] [dY] [sI2] 6 [tP9] [tpQ] e y I P [p5] 9 w [yoe]|9 e E [whdP5]| |o p [P8] [wP] [tP] [YP]|[wP] t [YP] q [ts] Y i||i o [p^] [qp] [tp] [yp]|[qP] e [oE] ( w y Y||Y i [o8] [wo] [to] [oY]|[wo] t [yo] [o9] e [tI] [yo]|p|y 5 9 e E|9 e E 5 9 e E y|o p [P8] [wP] [tP] [YP]|[wP] t [YP] 4 [s8] ( q e|i d ^ [qd] [dE] [yg]|[ge] t [ys] ( [PE] Y i||o p [P8] [wP] [tP] [yP]| |p [P6] ( [sE] [td]|D|d 2 6 9 w e y o p [tI2] 6 9 Q [se] Q [d9] 6 [D8] [wD] [yD] [YD]|[yd] [ts] [PE] [qp] t [pY] [iP]|[sE] t [yd] ^ [qD] [td] [yD] d [sY] [yP] [tp] [o@] ^ q w E o p P [s8] [ws] [ts] [ys]|[PE] [pe] [wo] [I9] e [tI] [yo]|[pe] t y [p5] 9 [pe] [pE] y P|o [whdP9]| |[z8] w [yl] [lY]|[wJ] y [lY] q t Y o ( t [og] [v(] 9 q [ec] [tc]|[eZ] w [ZQ] [wZ] [zy] o [zp]|y [oj] [wJ] [l%] [l(] [wl] [lW] l ( w [^J] [l6] ( [wl] [zt]|Z|Z 2 [z6] 9 w e 9 y 9 [sdG92]|[sdG9] 2 [spI92]|[odP92]|[oD8] [woD] [yoD] [oYD]|[yod] [tso] [oPE] [qpY] t [pY] [iP]|[soE] t [yod] ^ [qoD] [tod] [yoD] [od] [soY] [yoP] [tpi] [yo@] ^ q w E h j J [sl8] [wsl] [tsl] [ysl]|[PJE] [pje] [woh] [pg9] e [tpg] [yhd]|[sje] t y [l5] 9 [eJ] [JE] y l|z w y [od]Dg[ha]jJl [ys] [zo] [da] [toD] [oD] [odD] [oD]|[od] [so] [oP] [piY] s [hD] g g D s d E [oiD] [sod] [odD] [od] [soD] [odP] [spi] [yo(] E i o|h j J [sl8] [wsl] [tsl] [ysl]|[PJE] [wpj] [qoh] [pG9] e [tG] [yh]|[je] t y [jg5] 9 [jge] [jgE] y [PJ]|[oh] [wdP5]| |[d(] E Y o||o p [P4] 8 [yq] [PE] [p$] 9 [QI] e [o5] 9 w y o s d h [oda5]
]]