shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 3*24 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
6 [tupf] h G [tupf]
[6f] D [tup] f D [tup]
6 [tupf] h G [tupf]
[H6] j [tup] H j [tup]
6 [tupf] h G [tupf]
[6f] D [tup] s a [tup]
[0p] a [wrup] a [wru]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 [tupf] h G [tupf]
[6f] D [tup] f D [tup]
6 [tupf] h G [tupf]
[H6] j [tup] H j [tup]
6 [tupf] h G [tupf]
[6f] D [tup] s a [tup]
[0p] a [wrup] a [wru]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 f [Gtup] H j k [Ztup] k
[6j] [tupk] j [tup]
[6k] j [tup] j H [tup]
[6g] f [tup] f D [tup]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 f [Gtup] H j k [Ztup] k
[6j] [tupk] j [tup]
[6k] j [tup] j H [tup]
[6g] f [tup] f D [tup]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 [tupf] h G [tupf]
[6f] D [tup] [tup]
6 [tupf] h G [tupf]
[H6] j [tup] [tup]
6 [tupf] h G [tupf]
[6f] D [tup] [tup]
6 [tupf] h G [tupf]
[H6] j [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 f [Gtup] H j k [Ztup] k
[6j] [tupk] j [tup]
[6k] j [tup] j H [tup]
[6g] f [tup] f D [tup]
[6s] a [tupa] p [tup]
6 [tup] [tup]
6 f [Gtup] H j k [Ztup] k
[6j] [tupk] j [tup]
[6k] j [tup] j H [tup]
[6g] f [tup] f D [tup]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p [tup]
6 [tup] [tup]
s d [eyi] s a [eyi]
s d [eyi] s a [eyi]
[6s] a [tupa] p
]]