shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 2*25 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[skf]|k kk j k [skih]l[lf][lf]| |[skf] k k k j k [slihf]||[ywr8] [tie9] [yro9] [utqpf]|[pf] d sd [yrod0]||d [ws] [ta] [utsie9]ap os d|[ua]sa|[utro] [ytpi] [yuoa] [pi]sfsds[pf] [jf] j f [so0]d t [yd]o[od] h [tod] [t9]||o[wspi] d fh8wr|fhk[wfa8] [sge9] [rhd0] [usq4]pasa[se]a[spi5] [fe] [ts] [yuoa6][uoa]0 [wp] [ro] t[sh]y [5%] [sh]gY gD[t^] Ds[PD] g [hP]h[s5] [wt] [ywt]s[ytso] d f||8wr[yuo] o u [qf4]|[xljd] ttv[vlj4] [cW] x [hd^O]|W^[sgWO] W^[hdW] [ofa81]|[wp] f[ufa8] [ig] [ohd7] [s6]fl[te]0[te] [ykeda] [ye] [tshe] [sh92][pg][pg] e [tspi] [ed] [ts] [spf]| |[qpif4]dd Wq[yidWO] 4s[dW]s[i^]ODdd|z||[utsqpf]||f d sd[yrod0]|hod s a [tsie9]ap os d s[wura8]sa 5[yo81]u[yo]2[to3] [pif4] [pif8]ds[wp] [tpe]sfj l[kd][y0] [rh] [oj][jd]yh T[of] [tpid9]ss q[o4][spg5] [uha]wyd[ywuts8]ds w [ur81] [ti92] [to30] [usq4]pasa[se]a[wspi5] [wf] [ts] [yuoa6] 0 [wua] p [to] r [woh][oh][shO%]ggD[tYWD]s[^PD]g ^[^J]|[J5]hg[wth] [ywt]s[ytso] d f||[hfa81] w r [uokfa] [oh] [uf] [f4] 8 [xtlWH]v[vlYJ] [tcH]4[ZWH] [zv^H]|W^[lcWH] W^[zvWH] [ofa81]|[wa]f[ufa8] [ig] [ohd7] [s6]fl t [ykeda] [ye]0[tshe] [sh92][pg][pg]qe [tspi] [ed] [ts] ad| |[q4]|dd|Wq[ydW] 4s[d8]s[hd^O]Hg W^[YWD][ig]^[ohSD]% %|t [uaO] O%[oW]a[gda6]|t6[tsph]gy[spf]Y [^6] [hPJD]hh w[E7] [P7][ogd7]7 [ogd] [oD] [shD81]gD 8 1 [PD8] [gP92] [hP@(] [sqH4] [hP]t[gYO]g[toO] [oE] [gYW]P [dJ@(][hP] [gO]E[oPD]gh^[@(] [gd92] h [qH] [sgW8] [h9]2[qH]h[wsd5]|ss d f [tohfa]|a [kf]|h [spf]| |[tsqpf]|h[tsph] [yg] [YD] [poE]| |[sh] [hg] J [lh] [tolfa]Jhhw [f8][ofP]^g [hd] [s6]fl0 r [ytokd]|[hd] [hd92] [sg] 9 [tsie] d [s3] [oD4][id][id] q [ytqW4] 4 [s4] [shd^O]Hg q [ygWE] Y [ih] [hfa81] wr [uonk] [vh] [xf] [zlZHD]| |4 [O4] q|[tYW]|[soOD] [oD] [qoD] [so^D][idP][dP] W^[lgdW] W^[WJ]h[sfJ81]hhw[uE]f[ufP81] [ig] [ohd^] [s6]flos 6[kd6] o [sh5]6[ha2] [qpg] es[tspi] [ed] [ts] [qoOD4][idO][idO] t [yqdW] y [yd]s [o^WD][dO][id]|z||[toYP] P P P p P [tqoP] s [us] [us]|f [tYP] P P P p P [utsqp]| |s d f| |[a8]dwfhrwtw[yf]wtwrw[spf]| |[qf]to[to][po][tsph]o[tg]i[tf]ot[hd^O]qEqtq[ygP]qtq[hPE]q[of8]wtyu5[ufa81] [ig] [ohd7] [s6]fle0er[tkd]|[sh] [ysph9]e[yg]u ip [ig][uf][ts][pe] [qi] [O4]s8h[wg]Wti[sO] [dP] [sD] t W [hP5]9[wg]eEy[si] [id] [YD] 95 [soh6%] [ig](WE[ts] [yd] [YD%] [^O]dh[ig]| |[ig7]|s| |[oh851]|s s|s [tP%]|s [t^P] s| |[uso851]
]]