shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 3*24 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay
shared.nospacedelay = true

shared.scr = [[
[toD]| |D o D [yog]| |g o g [shY]| |h o h [siH]| |[oJD]| |[PJD%] ( W [PE] t|D g d [d^] q E t [yd] s s d D [o8] w t y [oY] P t Y [y5]| |d h Z [z8]|[dY]|o P z h c Z z| |d h Z [zg^J]|[yi]|o P d z h c Z z| |z Z c [vhW] Y O P [sl]|l l B V [vD] c [hZ] z Z c [zE] i [PJ] s [hd] g z h d D d s| |y o D [od8] w t Y i d o g [og] D d i|y o D [^D] d w E t y d o g g D d t y [ts] D J [PJ%] ( W E t P D H h E [tg] Y [iD]|D d D g [od^] q E t y i d i [d5] 9 w y [od] [YD] [yd] [YD] [igP%] ( W [ohE] [tD]||h D ^ q [dE] t y d d D [g8] w t [hY] [si]|o s 5 ( w E t D D d [pd$] 9 Q e t D D d [dO4] 8 q W t d D g [D5] 7 [od9] w r y [ohda] w y o d|[oh] [ZD] [zd] [gc] [hZD1] 5 8 ( w [ZJD(] [zdE] ( [g^] J c w [ZED] t y [tZD] [zyd] [toh] [h%] l Z v ( [lgcW] E [tlgc] E [tZD] E [slh5] 9 [wPJ] 9 E [PJ9] [wOH] [oh9] [OHD4] 8 q [ZD8] [ZWD] 8 q [oh8] [OH5] 9 w [gcJ9] [gcJE] 9 [wZD] [gc9] [h%] l Z v [VH(] [vth] [gc(] E [ZD(] [zdE] [JB(] ^ q E q [oED] [qd] [ED] [qoh] [sg1] 5 [oD8] ( w [oD(] [wd] [h(] [og^] w [ED] t y [tsD] [yJ] [tsH] [sH%] [shO(] [shWO] [sgOE] [tsgO] [soED] [tsoD] [hPE] [og5] 9 [wod] 9 E 9 [wod]|[tqdW] D d o [ywd] D d o [sYW] o [dE] o [tD] o d|[yw84] Y y w [y95] Y y w [t%] @ [Y%] @ [wti^] 4 [ywo^] 4 [Y1] y [Y5] w [Y8] y [Y5] w [Y(] y [Y5] w [Y8] y [Y5] w [^Y] y [Y5] w [^Y] y [Y8] w [Y9] y [Y8] w [Y9] y [Y8] w [Y%] y [Y@] w [Y%] y [^Y] w [Y8] y [^Y] w [Y8] y [^Y] w [^Y] w [i4] w [o^] w [i4] w [Y8] w [y4] w [^Y] w [i4] w [o1] w [t5] o [w8] t [o5] w [o(] w [o5] w [t8] O [w5] w [o^] w [t5] o [w^] t [o5] w [t8] o [w5] ^ [o5] O [o%] w [i@] w [Y%] w [y^] w [Y8] w [i^] 8 ^ [o^Y] [iO4] [o^P] [sO4] [d^P] [PD4] [gd^P] [hPD4] [tso1]| |m v v V c c v m m l s t 8
]]